export const COUNTRIES = [
  'Uzbekistan',
  'Kazakhstan',
  'Kyrgyzstan',
  'Tajikistan',
  'Turkmenistan',
  'Russia',
  'Turkey',
  'China',
  'India',
  'Pakistan',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Oman',
  'Azerbaijan',
  'Georgia',
  'Armenia',
  'Belarus',
  'Ukraine',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'United Kingdom',
  'United States',
  'South Korea',
  'Japan',
] as const;
